# Generated by Django 5.2.8 on 2025-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activeKt',
            field=models.BooleanField(default=False),
        ),
    ]
